// TalentFlow Version Configuration
// Convention: v0.X.Y — X = feature group, Y = bugfix/polish

export const APP_VERSION = 'v0.14.0'
export const APP_ENV: 'beta' | 'production' = 'beta'
export const APP_NAME = 'TalentFlow'

export interface ChangelogEntry {
  version: string
  date: string
  label?: string
  features: string[]
}

export const CHANGELOG: ChangelogEntry[] = [
  {
    version: 'v0.14.0',
    date: '2026-03-22',
    label: 'Recherche full-text & Audit IA',
    features: [
      'Recherche full-text dans TOUT : compétences, expériences, formations, CV brut, notes, résumé IA',
      'Recherche sans accents : "beton" trouve "béton", "macon" trouve "maçon"',
      'Recherche multi-mots flexible et rapide (RPC PostgreSQL)',
      'Outil Analyser Candidats : audit qualité de la base (photos, CVs, fiches incomplètes)',
      'Analyse approfondie IA avec Claude Vision (classification documents, vérification photos)',
      'Bouton Corriger tous les "Candidat" : re-parsing en masse avec vision',
      'Demandes d\'accès sous Administration avec badge compteur',
      'Notification email lors d\'une nouvelle demande d\'accès',
      'Documents : changer catégorie (dropdown), définir comme CV principal, supprimer',
      'Pagination serveur (20/50/100 candidats) au lieu de tout charger',
      'Page mémorisée : retour à la même page après consultation d\'une fiche',
      'Boutons Valider/Archiver/À traiter disponibles sur tous les statuts',
      'Crop photo manuel depuis le CV (sélection de zone)',
    ],
  },
  {
    version: 'v0.13.0',
    date: '2026-03-22',
    label: 'UI Polish & Outils',
    features: [
      'Nouveau hub Outils dans la sidebar (Import en masse, Corriger photos, Analyser doublons)',
      'Mode sombre : tous les fonds blancs corriges (candidats, dialogs, CV, tags)',
      'Dashboard : carte Candidats sans surbrillance, animation NumberTicker toujours visible',
      'TopBar visible sur la liste candidats (toggle theme + profil)',
      'Boutons uniformises en jaune sur toute l\'application',
      'Fiche candidat : icones toolbar CV avec bouton Imprimer, tags competences et langues colores',
      'Resume IA : fond adaptatif clair/sombre',
      'Navigation retour vers Outils sur les 3 pages outils',
      'Import en masse : boutons jaunes, texte mis a jour',
      'Doublons : suppression du rectangle vide en etat initial',
      'Corriger photos : cartes statistiques style KPI dashboard',
    ],
  },
  {
    version: 'v0.12.0',
    date: '2026-03-22',
    label: 'Import intelligent & Documents',
    features: [
      'Classification IA des documents (CV, certificat, diplome, formation, attestation, permis)',
      'Import 2 passes : CVs traites en premier, documents rattaches ensuite automatiquement',
      'Auto-actualisation des doublons (plus de confirmation manuelle)',
      'Import en arriere-plan avec barre minimisee visible sur toutes les pages',
      'Bouton Arreter pour annuler un import en cours',
      'Panel Documents complet avec categories depliables et drag & drop',
      'Upload de nouveau CV depuis Documents (ancien sauvegarde automatiquement)',
      'Choix du CV principal a afficher dans le preview',
      'Re-parsing CV additif : fusionne experiences/competences au lieu de remplacer',
      'Photo extraite uniquement des CVs (pas des certificats/logos)',
      'Photo jamais remplacee si deja presente',
      'Affichage "Pas de CV" avec emoji quand pas de CV disponible',
    ],
  },
  {
    version: 'v0.11.0',
    date: '2026-03-22',
    label: 'Zoom HD & Etoiles',
    features: [
      'Zoom CV qualite HD (iframe agrandie, pas transform:scale)',
      'Scroll molette + drag main sur CV zoome et preview',
      'Preview CV multi-pages scrollable dans la liste candidats',
      'Score etoiles 0-5 sur les candidats (liste + fiche)',
      'Bouton Re-analyser IA pour relancer le parsing CV',
      'Section Documents dans la fiche candidat',
      'Dropdown statut (A traiter / Actif / Archive) remplace sous-menu sidebar',
      'Recherche multi-mots flexible (accents ignores, ordre libre)',
      'Recherche persistante via sessionStorage',
      'Rotation CV dans le preview liste candidats',
      'Sidebar reste orange sur toutes les sous-pages',
      'Modal suppression candidat centre (au lieu du menu 3 points)',
      'Bouton "Importer Candidat/s" au lieu de "Importer CV"',
      'Pipeline supprime de l\'import',
    ],
  },
  {
    version: 'v0.10.0',
    date: '2026-03-21',
    label: 'Workflow & Doublons',
    features: [
      'Candidats a traiter : workflow de verification avant mise en base active',
      'Bouton Valider dans la fiche candidat pour passer en base active',
      'Badge sidebar avec compteur de candidats a traiter',
      'Fusion intelligente des doublons (combine le max d\'infos des deux profils)',
      'Doublons groupes par candidat (clusters de profils identiques)',
      'Fusion manuelle depuis la fiche candidat (menu 3 points → Fusionner avec)',
      'Bouton "Personnes differentes" au lieu de "Ignorer"',
      'Pause/Reprise/Recommencer sur l\'analyse doublons',
      'Historique detaille des paires ignorees avec noms',
      'Analyse photos : pause/reprise + re-analyser tout',
      'Impression CV via proxy (compatible tous navigateurs)',
      'Lightbox CV plein ecran a 100%',
      'Notes et Infos en panneau lateral slide-in',
      'Log d\'import groupe par session avec erreurs detaillees',
      'Retry import qui relance le worker automatiquement',
      'Menu 3 points dans la fiche candidat (Notes, Infos, Fusionner, Supprimer)',
    ],
  },
  {
    version: 'v0.9.0',
    date: '2026-03-21',
    label: 'Photos & Logs',
    features: [
      'Extraction photos intelligente avec scoring (portraits uniquement)',
      'Correction photos en masse depuis Parametres',
      'Logs d\'activite avec pagination et filtre erreurs',
      'Upload/suppression de photo candidat',
      'Age plus visible sur les fiches candidats',
      'Dropdown pagination deplace en haut',
      'Filtres avances ameliores (Permis de Conduire)',
    ],
  },
  {
    version: 'v0.8.0',
    date: '2026-03-18',
    label: 'Import en masse',
    features: [
      'Import en masse de milliers de CVs (ZIP, dossiers)',
      'Traitement concurrent avec web worker (6 threads)',
      'Detection de doublons automatique',
      'Gestion des erreurs avec retry automatique',
      'Progression temps reel dans la sidebar',
      'Export CSV des resultats d\'import',
      'Categories automatiques par dossier',
    ],
  },
  {
    version: 'v0.7.0',
    date: '2026-03-14',
    label: 'Securite & Email',
    features: [
      'Authentification 2FA par email (OTP HMAC-SHA256)',
      'SMTP Resend pour emails transactionnels',
      'Templates email en francais (Supabase)',
      'Deconnexion securisee (cookies httpOnly)',
      'Systeme de demandes d\'acces',
    ],
  },
  {
    version: 'v0.6.0',
    date: '2026-03-10',
    label: 'Microsoft 365',
    features: [
      'Integration Microsoft 365 (OAuth 2.0)',
      'Synchronisation emails Outlook',
      'Import automatique de CVs depuis emails',
      'Creation de candidats depuis pieces jointes',
      'Deconnexion Microsoft',
    ],
  },
  {
    version: 'v0.5.0',
    date: '2026-03-05',
    label: 'Communications',
    features: [
      'Envoi d\'emails aux candidats',
      'Templates d\'email personnalisables',
      'Integration WhatsApp Business',
      'Envoi SMS/iMessage',
      'Historique des communications',
    ],
  },
  {
    version: 'v0.4.0',
    date: '2026-02-28',
    label: 'Pipeline & Matching',
    features: [
      'Pipeline Kanban (drag & drop)',
      'Etapes : Nouveau, Contacte, Entretien, Place, Refuse',
      'Matching IA candidat/offre (score detaille)',
      'Recherche semantique IA (Claude)',
      'Gestion des entretiens (planning, types, statuts)',
    ],
  },
  {
    version: 'v0.3.0',
    date: '2026-02-20',
    label: 'Offres & Dashboard',
    features: [
      'Creation et gestion des offres d\'emploi',
      'Publication vers Job-Room.ch',
      'Dashboard KPI (candidats, offres, entretiens, places)',
      'Carte geographique des candidats',
      'Widget candidats recents',
    ],
  },
  {
    version: 'v0.2.0',
    date: '2026-02-12',
    label: 'IA & CV',
    features: [
      'Analyse de CV par Claude AI',
      'Extraction automatique : nom, email, telephone, competences',
      'Support PDF, DOCX, DOC, TXT, JPG, PNG',
      'Preview CV avec zoom, scroll, pan',
      'Stockage Supabase Storage',
      'Extraction de photos depuis les PDFs',
    ],
  },
  {
    version: 'v0.1.0',
    date: '2026-02-01',
    label: 'Fondations',
    features: [
      'Architecture Next.js 14 + Supabase',
      'Authentification email/mot de passe',
      'Liste des candidats avec recherche et filtres',
      'Fiche candidat detaillee',
      'CRUD candidats complet',
      'Interface L\'Agence SA (theme noir & jaune)',
      'Parametres utilisateur',
      'Navigation sidebar',
    ],
  },
]
