// TalentFlow Version Configuration
// Convention: v0.X.Y — X = feature group, Y = bugfix/polish

export const APP_VERSION = 'v0.20.0'
export const APP_ENV: 'beta' | 'production' = 'beta'
export const APP_NAME = 'TalentFlow'

export interface ChangelogEntry {
  version: string
  date: string
  label?: string
  features: string[]
}

export const CHANGELOG: ChangelogEntry[] = [
  {
    version: 'v0.20.0',
    date: '2026-03-26',
    label: 'Outlook per-user, Securite & Fixes',
    features: [
      'Outlook per-user : chaque utilisateur connecte son propre compte Outlook dans Parametres',
      'Envois : chaque user envoie depuis sa propre adresse (plus de compte partage)',
      'Securite : page Integrations (OneDrive) bloquee au niveau middleware pour j.barbosa uniquement',
      'Securite : blocage URL directe /integrations pour tous sauf admin',
      'Sidebar : Integrations masquee pour les non-admins',
      'Re-analyser IA : correction contrainte genre (M/F → homme/femme)',
      'Re-analyser IA : date de naissance isolee dans coordonnees suisses maintenant detectee',
      'Retour aux candidats : plus besoin de double-clic apres re-analyse',
      'CV personnalise : style section redesigne (ligne fine, categorie au-dessus)',
      'Doublons : plus dinformations dans la carte (experiences, formations, age)',
      'Fusion : explication claire du role du profil principal vs choix des champs',
      'Activite imports : fix affichage onglet Imports OneDrive',
    ],
  },
  {
    version: 'v0.19.0',
    date: '2026-03-26',
    label: 'OneDrive Sync & Activite',
    features: [
      'Sync OneDrive : log individuel par CV importe/actualise dans Activite',
      'Activite : onglet Imports affiche les 90+ imports OneDrive en detail',
      'Fix type error candidatId/filename dans la route sync OneDrive',
      'Historique candidat : correction affichage (photo vs formations)',
    ],
  },
  {
    version: 'v0.18.0',
    date: '2026-03-26',
    label: 'Doublons enrichis & Fusion',
    features: [
      'Doublons : carte enrichie avec experiences, formations, age, badges exp/form',
      'Doublons : boutons Profil A et Profil B pour ouvrir les deux fiches',
      'Doublons : image cassee remplacee par initiales',
      'Fusion : score de certitude et raisons de similarite dans la modale',
      'Fusion : champs supplementaires (date de naissance, annees exp)',
    ],
  },
  {
    version: 'v0.17.0',
    date: '2026-03-26',
    label: 'CV Brande & Fix Build',
    features: [
      'CV personnalise : sections avec ligne fine jaune (plus de bandeau plein)',
      'CV personnalise : categorie positionnee au-dessus de la ligne',
      'Fix build Vercel : erreur TypeScript route sync OneDrive',
      'Tag v0.20.0-stable pointe sur le dernier commit stable',
    ],
  },
  {
    version: 'v0.16.1',
    date: '2026-03-26',
    label: 'CV, Doublons & Activites OneDrive',
    features: [
      'CV personnalise : titres de section au-dessus de la ligne jaune (plus lisible)',
      'Doublons : tags raisons avec retour a la ligne (plus de debordement)',
      'Doublons : carte candidat enrichie (competences, nom du CV)',
      'Activites Imports : chaque CV importe/actualise depuis OneDrive est logge individuellement',
      'Activites : onglet Imports affiche maintenant les imports OneDrive en detail',
    ],
  },
  {
    version: 'v0.16.0',
    date: '2026-03-24',
    label: 'Mailing Geo & Activites',
    features: [
      'Mailing : filtre distance geographique avec autocompletion (Nominatim/OpenStreetMap)',
      'Mailing : rayon kilometrique configurable (10 / 20 / 50 / 100 / 200 km)',
      'Mailing : tri automatique des clients du plus proche au plus loin',
      'Mailing : badge km code-couleur (vert < 20km, orange < 50km, gris au-dela)',
      'Mailing : clients sans email toujours en bas de liste',
      'Mailing : secteurs/metiers tries A-Z dans la liste deroulante',
      'Mailing : une seule checkbox par client (email boite), contacts selectionnables independamment',
      'Mailing : bouton lien externe pour ouvrir la fiche client sans fermer la modale',
      'Activites : onglet Pipeline (changements de statut)',
      'Activites : onglet Messages (emails, WhatsApp, SMS, CV envoyes)',
      'Activites : onglet Candidats remplace CV (imports + modifications)',
      'Activites : filtre par plage de dates (du/au)',
      'Activites : multi-selection avec tout selectionner / tout deselectionner',
      'Activites : bouton Vider l\'onglet avec confirmation modale',
      'Pipeline : bouton X rouge sur les cartes pour retirer un candidat du pipeline',
      'Pipeline : surbrillance des colonnes corrigee (fonctionne meme avec des cartes dans la colonne)',
      'Pipeline : colonne Refuse plus coupee a l\'affichage',
      'Pipeline : bouton Retour contextuel (Retour au pipeline / Retour aux candidats)',
      'Pipeline : suppression de la fleche orange (doublon du bouton oeil)',
    ],
  },
  {
    version: 'v0.15.0',
    date: '2026-03-23',
    label: 'Clients, Mailing & Activite',
    features: [
      'Module Clients complet : 1207 entreprises importees depuis QUADRIGIS avec 538 contacts',
      'Fiche client : infos, adresse, secteur, notes, personnes de contact (nom, fonction, tel, email)',
      'Filtres avances clients : secteur, ville, canton, NPA, avec/sans contacts',
      'Vue grille/liste sur Clients avec persistance recherche',
      'Mailing en masse : selection candidats + CV personnalise auto en piece jointe',
      'Personnaliseur CV : sections toggleables, champs editables, apercu PDF temps reel',
      'Bouton "Joindre au mail" (vert) directement depuis le formulaire envois',
      'CV PDF brande L-Agence : header recruteur, footer bureau, permis de conduire',
      'Dashboard : KPI Clients, graphique candidatures recues (jour/semaine/mois)',
      'Fil d\'activite : timeline collaborative, filtres par type, notes editables',
      'Widget activite recente sur dashboard (refresh 30s)',
      'Pipeline redesigne : Kanban couleurs, drag & drop ameliore, recherche, actions rapides',
      'Entretiens redesignes : calendrier semaine, grille horaire, events couleur par type',
      'Affichage 100/500/1000/Tous candidats sur une seule page',
      'Reset selection automatique lors de recherche/changement filtres',
      'Bouton "Tout deselectionner" noir',
      'App mobile : login redesigne, pagination 4000+ candidats, OTA updates',
      'PWA installable depuis le navigateur',
      'Sidebar : Clients, Activite, Envois (renomme)',
    ],
  },
  {
    version: 'v0.14.0',
    date: '2026-03-22',
    label: 'Recherche full-text & Audit IA',
    features: [
      'Recherche full-text dans TOUT : compétences, expériences, formations, CV brut, notes, résumé IA',
      'Recherche sans accents : "beton" trouve "béton", "macon" trouve "maçon"',
      'Recherche multi-mots flexible et rapide (RPC PostgreSQL)',
      'Outil Analyser Candidats : audit qualité de la base (photos, CVs, fiches incomplètes)',
      'Analyse approfondie IA avec Claude Vision (classification documents, vérification photos)',
      'Bouton Corriger tous les "Candidat" : re-parsing en masse avec vision',
      'Demandes d\'accès sous Administration avec badge compteur',
      'Notification email lors d\'une nouvelle demande d\'accès',
      'Documents : changer catégorie (dropdown), définir comme CV principal, supprimer',
      'Pagination serveur (20/50/100 candidats) au lieu de tout charger',
      'Page mémorisée : retour à la même page après consultation d\'une fiche',
      'Boutons Valider/Archiver/À traiter disponibles sur tous les statuts',
      'Crop photo manuel depuis le CV (sélection de zone)',
    ],
  },
  {
    version: 'v0.13.0',
    date: '2026-03-22',
    label: 'UI Polish & Outils',
    features: [
      'Nouveau hub Outils dans la sidebar (Import en masse, Corriger photos, Analyser doublons)',
      'Mode sombre : tous les fonds blancs corriges (candidats, dialogs, CV, tags)',
      'Dashboard : carte Candidats sans surbrillance, animation NumberTicker toujours visible',
      'TopBar visible sur la liste candidats (toggle theme + profil)',
      'Boutons uniformises en jaune sur toute l\'application',
      'Fiche candidat : icones toolbar CV avec bouton Imprimer, tags competences et langues colores',
      'Resume IA : fond adaptatif clair/sombre',
      'Navigation retour vers Outils sur les 3 pages outils',
      'Import en masse : boutons jaunes, texte mis a jour',
      'Doublons : suppression du rectangle vide en etat initial',
      'Corriger photos : cartes statistiques style KPI dashboard',
    ],
  },
  {
    version: 'v0.12.0',
    date: '2026-03-22',
    label: 'Import intelligent & Documents',
    features: [
      'Classification IA des documents (CV, certificat, diplome, formation, attestation, permis)',
      'Import 2 passes : CVs traites en premier, documents rattaches ensuite automatiquement',
      'Auto-actualisation des doublons (plus de confirmation manuelle)',
      'Import en arriere-plan avec barre minimisee visible sur toutes les pages',
      'Bouton Arreter pour annuler un import en cours',
      'Panel Documents complet avec categories depliables et drag & drop',
      'Upload de nouveau CV depuis Documents (ancien sauvegarde automatiquement)',
      'Choix du CV principal a afficher dans le preview',
      'Re-parsing CV additif : fusionne experiences/competences au lieu de remplacer',
      'Photo extraite uniquement des CVs (pas des certificats/logos)',
      'Photo jamais remplacee si deja presente',
      'Affichage "Pas de CV" avec emoji quand pas de CV disponible',
    ],
  },
  {
    version: 'v0.11.0',
    date: '2026-03-22',
    label: 'Zoom HD & Etoiles',
    features: [
      'Zoom CV qualite HD (iframe agrandie, pas transform:scale)',
      'Scroll molette + drag main sur CV zoome et preview',
      'Preview CV multi-pages scrollable dans la liste candidats',
      'Score etoiles 0-5 sur les candidats (liste + fiche)',
      'Bouton Re-analyser IA pour relancer le parsing CV',
      'Section Documents dans la fiche candidat',
      'Dropdown statut (A traiter / Actif / Archive) remplace sous-menu sidebar',
      'Recherche multi-mots flexible (accents ignores, ordre libre)',
      'Recherche persistante via sessionStorage',
      'Rotation CV dans le preview liste candidats',
      'Sidebar reste orange sur toutes les sous-pages',
      'Modal suppression candidat centre (au lieu du menu 3 points)',
      'Bouton "Importer Candidat/s" au lieu de "Importer CV"',
      'Pipeline supprime de l\'import',
    ],
  },
  {
    version: 'v0.10.0',
    date: '2026-03-21',
    label: 'Workflow & Doublons',
    features: [
      'Candidats a traiter : workflow de verification avant mise en base active',
      'Bouton Valider dans la fiche candidat pour passer en base active',
      'Badge sidebar avec compteur de candidats a traiter',
      'Fusion intelligente des doublons (combine le max d\'infos des deux profils)',
      'Doublons groupes par candidat (clusters de profils identiques)',
      'Fusion manuelle depuis la fiche candidat (menu 3 points → Fusionner avec)',
      'Bouton "Personnes differentes" au lieu de "Ignorer"',
      'Pause/Reprise/Recommencer sur l\'analyse doublons',
      'Historique detaille des paires ignorees avec noms',
      'Analyse photos : pause/reprise + re-analyser tout',
      'Impression CV via proxy (compatible tous navigateurs)',
      'Lightbox CV plein ecran a 100%',
      'Notes et Infos en panneau lateral slide-in',
      'Log d\'import groupe par session avec erreurs detaillees',
      'Retry import qui relance le worker automatiquement',
      'Menu 3 points dans la fiche candidat (Notes, Infos, Fusionner, Supprimer)',
    ],
  },
  {
    version: 'v0.9.0',
    date: '2026-03-21',
    label: 'Photos & Logs',
    features: [
      'Extraction photos intelligente avec scoring (portraits uniquement)',
      'Correction photos en masse depuis Parametres',
      'Logs d\'activite avec pagination et filtre erreurs',
      'Upload/suppression de photo candidat',
      'Age plus visible sur les fiches candidats',
      'Dropdown pagination deplace en haut',
      'Filtres avances ameliores (Permis de Conduire)',
    ],
  },
  {
    version: 'v0.8.0',
    date: '2026-03-18',
    label: 'Import en masse',
    features: [
      'Import en masse de milliers de CVs (ZIP, dossiers)',
      'Traitement concurrent avec web worker (6 threads)',
      'Detection de doublons automatique',
      'Gestion des erreurs avec retry automatique',
      'Progression temps reel dans la sidebar',
      'Export CSV des resultats d\'import',
      'Categories automatiques par dossier',
    ],
  },
  {
    version: 'v0.7.0',
    date: '2026-03-14',
    label: 'Securite & Email',
    features: [
      'Authentification 2FA par email (OTP HMAC-SHA256)',
      'SMTP Resend pour emails transactionnels',
      'Templates email en francais (Supabase)',
      'Deconnexion securisee (cookies httpOnly)',
      'Systeme de demandes d\'acces',
    ],
  },
  {
    version: 'v0.6.0',
    date: '2026-03-10',
    label: 'Microsoft 365',
    features: [
      'Integration Microsoft 365 (OAuth 2.0)',
      'Synchronisation emails Outlook',
      'Import automatique de CVs depuis emails',
      'Creation de candidats depuis pieces jointes',
      'Deconnexion Microsoft',
    ],
  },
  {
    version: 'v0.5.0',
    date: '2026-03-05',
    label: 'Communications',
    features: [
      'Envoi d\'emails aux candidats',
      'Templates d\'email personnalisables',
      'Integration WhatsApp Business',
      'Envoi SMS/iMessage',
      'Historique des communications',
    ],
  },
  {
    version: 'v0.4.0',
    date: '2026-02-28',
    label: 'Pipeline & Matching',
    features: [
      'Pipeline Kanban (drag & drop)',
      'Etapes : Nouveau, Contacte, Entretien, Place, Refuse',
      'Matching IA candidat/offre (score detaille)',
      'Recherche semantique IA (Claude)',
      'Gestion des entretiens (planning, types, statuts)',
    ],
  },
  {
    version: 'v0.3.0',
    date: '2026-02-20',
    label: 'Offres & Dashboard',
    features: [
      'Creation et gestion des offres d\'emploi',
      'Publication vers Job-Room.ch',
      'Dashboard KPI (candidats, offres, entretiens, places)',
      'Carte geographique des candidats',
      'Widget candidats recents',
    ],
  },
  {
    version: 'v0.2.0',
    date: '2026-02-12',
    label: 'IA & CV',
    features: [
      'Analyse de CV par Claude AI',
      'Extraction automatique : nom, email, telephone, competences',
      'Support PDF, DOCX, DOC, TXT, JPG, PNG',
      'Preview CV avec zoom, scroll, pan',
      'Stockage Supabase Storage',
      'Extraction de photos depuis les PDFs',
    ],
  },
  {
    version: 'v0.1.0',
    date: '2026-02-01',
    label: 'Fondations',
    features: [
      'Architecture Next.js 14 + Supabase',
      'Authentification email/mot de passe',
      'Liste des candidats avec recherche et filtres',
      'Fiche candidat detaillee',
      'CRUD candidats complet',
      'Interface L\'Agence SA (theme noir & jaune)',
      'Parametres utilisateur',
      'Navigation sidebar',
    ],
  },
]
