// TalentFlow Version Configuration
// Convention: MAJOR.MINOR.PATCH (semver)

export const APP_VERSION = '1.8.11'
export const APP_ENV: 'beta' | 'production' = 'production'
export const APP_NAME = 'TalentFlow'

export interface ChangelogEntry {
  version: string
  date: string
  label?: string
  features: string[]
}

export const CHANGELOG: ChangelogEntry[] = [
  {
    version: '1.8.3',
    date: '2026-04-12',
    label: 'Secrétariat — Notifications + Filtres + ALFA unifié',
    features: [
      'Notifications : badge cloche affiche le nombre exact, suppression limite 100',
      'Notifications : clic sur alerte navigue vers l\'onglet/filtre concerné',
      'AlertModal : champ date & heure de rappel (date_rappel en DB)',
      'ALFA : les deux tables (Suivi + À Payer) affichées sur la même page',
      'Candidats : pills de filtre (Tous / Permis urgents / À renouveler / Docs manquants)',
      'Dashboard : noms cliquables vers la fiche candidat',
      'Sidebar : badge notifications en rouge',
      'Modal candidat : champ Carte d\'identité supprimé',
    ],
  },
  {
    version: '1.8.2',
    date: '2026-04-12',
    label: 'Secrétariat — UI nettoyée, photos carrées',
    features: [
      'Suppression filtres Excel (ColumnFilter) partout : Candidats, Accidents, ALFA Suivi, ALFA À Payer',
      'Photos carrées (44×44, borderRadius 8) sur tous les onglets, ajoutées sur ALFA Suivi',
      'ALFA : colonne N° AVS séparée supprimée, affiché sous le nom',
      'Tri par flèches conservé sur toutes les colonnes',
    ],
  },
  {
    version: '1.8.1',
    date: '2026-04-12',
    label: 'Secrétariat — Archives + UI ALFA',
    features: [
      'Accidents : bouton archive (📦) sur cas terminés, badge archivé',
      'ALFA À Payer : noms cliquables (lien candidat), avatars photo, suppression boutons tri Récent/A→Z/Z→A',
      'Couleurs : simplifié à 4 couleurs (Vert, Bleu, Jaune, Rouge) + Aucune',
    ],
  },
  {
    version: '1.8.0',
    date: '2026-04-12',
    label: 'Notifications Secrétariat + Case Suisse',
    features: [
      'Notifications : fix route marquer lu (/lu), création route mark-all-read',
      'Notifications : déduplication côté serveur (type + reference_id)',
      'Notifications : alertes auto — permis urgent (<30j), surveillance (<90j), sinistre >30j, docs manquants',
      'Notifications : séparation panel Messages / Alertes automatiques',
      'Notifications : modal "Ajouter une alerte" avec type, titre, message, candidat, urgence',
      'Notifications : colonnes urgence, created_by, created_by_nom en DB (reference_id text)',
      'Sidebar : fix badge secrétariat (query cassée → d.notifications.length)',
      'Suivi candidats : colonne "suisse" + case à cocher 🇨🇭 dans table et modal',
      'Fix couleur 2025 : default DB corrigé (normal → null), 341 entrées nettoyées',
    ],
  },
  {
    version: '1.7.4',
    date: '2026-04-12',
    label: 'Corrections Secrétaire',
    features: [
      'Fix email doublon reset password : passage par admin API (plus de notification Supabase)',
      'Sidebar Secrétaire : masquer Pipeline, Envois, Commandes, Matching IA, Activité',
      'Secrétariat visible pour Admin dans la sidebar',
      'Historique modifications secrétariat : table logs_secretariat + bouton Historique + panel',
      'Logging automatique sur les 5 routes PATCH/DELETE secrétariat (avant/après)',
    ],
  },
  {
    version: '1.7.3',
    date: '2026-04-12',
    label: 'Fix reset password redirect',
    features: [
      'AuthHashHandler détecte type=recovery dans le hash Supabase et redirige vers /reset-password',
      'Le lien email de réinitialisation arrive correctement sur la page de saisie du nouveau mot de passe',
    ],
  },
  {
    version: '1.7.2',
    date: '2026-04-12',
    label: 'Reset mot de passe',
    features: [
      'Lien "Mot de passe oublié ?" sur la page login',
      'Formulaire de demande de réinitialisation par email (Supabase resetPasswordForEmail)',
      'Page /reset-password pour saisir le nouveau mot de passe après clic sur le lien email',
    ],
  },
  {
    version: '1.7.1',
    date: '2026-04-12',
    label: 'Module ALFA Secrétariat',
    features: [
      'Import données ALFA 2025/2026 (180 entrées) et ALFA à payer (76 entrées) depuis Excel',
      'Onglet ALFA dans le module Secrétariat avec sous-vues Suivi / À Payer',
      'Tables secretariat_alfa et secretariat_alfa_paiements avec RLS',
      'API routes GET/POST/PATCH/DELETE pour alfa et alfa-paiements',
      'AlfaTable et AlfaPaiementsTable avec données complètes',
      'Restructuration onglets : Suivi Candidats, ALFA, Accidents & Maladies, Loyer',
      'CSS kpi-red et kpi-orange ajoutés dans dashboard.css',
      'Colonnes loyer (mode_paiement, hotel_auberge, mois, date_deduction) mises à jour',
    ],
  },
  {
    version: '1.7.0',
    date: '2026-04-12',
    label: 'Dashboard Secrétaire',
    features: [
      '📊 Dashboard dédié rôle Secrétaire (dashboard/page.tsx conditionnel)',
      '📊 Alertes urgentes : permis < 30j, permis < 90j, accidents en cours',
      '📊 4 KPIs : candidats actifs, permis urgents, permis surveillance, accidents',
      '📊 Liste "À traiter aujourd\'hui" priorisée rouge/orange/jaune avec actions WhatsApp/Email',
      '📊 Accès rapides : nouveau candidat, déclarer accident, rechercher',
      '📊 Activité récente : 5 dernières modifications secrétariat',
      '📊 Route GET /api/secretariat/dashboard-stats',
    ],
  },
  {
    version: '1.6.9',
    date: '2026-04-12',
    label: 'Module Secrétariat complet',
    features: [
      '📋 Nouveau module Secrétariat (accès rôle Secrétaire uniquement)',
      '📋 4 tables DB : secretariat_candidats, secretariat_accidents, secretariat_loyers, secretariat_notifications',
      '📋 Onglet Candidats : suivi docs, permis coloré, AVS/IBAN masqués, indicateur statut ligne',
      '📋 Onglet Accidents & Maladies : cards avec timeline, couleur ligne, statut terminé',
      '📋 Onglet Loyers : tableau adresse, montant CHF, dates',
      '📋 Notifications auto (permis expirant, docs manquants) + badge sidebar orange',
      '📋 9 routes API secretariat + route import masse JSON',
      '📋 Sidebar : entrée Secrétariat (ClipboardList) visible uniquement rôle Secrétaire',
      '📋 Middleware : /secretariat ajouté aux routes protégées',
    ],
  },
  {
    version: '1.6.8',
    date: '2026-04-12',
    label: 'Missions UI — photos & largeur',
    features: [
      '🎨 Missions : avatars 36×36 → 48×48px',
      '🎨 Missions : textes agrandis (nom 13→15, client 13→14, marge 13→15)',
      '🎨 d-page max-width 1200 → 1400px (toutes les pages)',
      '🎨 Missions : suppression override maxWidth:960',
    ],
  },
  {
    version: '1.6.7',
    date: '2026-04-12',
    label: 'UI — cohérence titres & icônes toutes pages',
    features: [
      '🎨 Page Missions centrée (d-content → d-page, maxWidth 960)',
      '🎨 Icônes Lucide sur tous les titres de pages (TrendingUp, Building2, GitBranch, Send, Sparkles, UserCheck, Briefcase, Plug, Users)',
      '🎨 Harmonisation titres/sous-titres : classes CSS d-page-title + d-page-sub sur toutes les pages',
      '🔤 Fix typo "Integrations" → "Intégrations"',
    ],
  },
  {
    version: '1.6.6',
    date: '2026-04-12',
    label: 'Suppression sync Quadrigis',
    features: [
      '🗑️ Suppression complète sync Quadrigis automatique (5 routes API, PendingPanel, badge sidebar)',
      '🗑️ DROP TABLE missions_pending + DROP COLUMN numero_quadrigis',
      '🧹 Page Missions : onglets simplifiés (Missions | Bilan uniquement)',
    ],
  },
  {
    version: '1.6.5',
    date: '2026-04-12',
    label: 'Sentry fix Turbopack + alertes',
    features: [
      '🔧 Fix Sentry : instrumentation-client.ts pour compatibilité Turbopack (sentry.client.config.ts ignoré)',
      '🔧 instrumentation.ts ajouté (server + edge configs)',
      '🔔 2 alertes Sentry configurées : nouvelle erreur + erreur récurrente (>3x/h)',
      '🧹 Bouton test Sentry supprimé du dashboard',
    ],
  },
  {
    version: '1.6.4',
    date: '2026-04-12',
    label: 'Sentry — monitoring erreurs production',
    features: [
      '🔍 Sentry intégré (@sentry/nextjs) : client, server, edge configs',
      '🔍 Source maps uploadées automatiquement au build (silent mode)',
      '🔍 Replay activé sur erreurs (replaysOnErrorSampleRate: 1.0)',
      '🔍 Traces échantillonnées à 10% (tracesSampleRate: 0.1)',
    ],
  },
  {
    version: '1.6.3',
    date: '2026-04-12',
    label: 'Audit complet ADMIN_EMAIL .trim()',
    features: [
      '🔧 .trim() ajouté sur toutes les occurrences ADMIN_EMAIL restantes (app/admin/route.ts)',
      '🔧 Audit 7 fichiers : 5 déjà corrigés (v1.6.2), 1 hardcodé (Sidebar), 1 corrigé ici',
    ],
  },
  {
    version: '1.6.2',
    date: '2026-04-12',
    label: 'Fix régressions v1.6.1 + Sidebar Sécurité',
    features: [
      '🔧 Fix Bug 1 : middleware.ts ADMIN_EMAIL — fallback + .trim() restaurés (intégrations inaccessibles)',
      '🔧 Fix Bug 2 : api/admin/users — .trim() sur ADMIN_EMAIL (accès réservé administrateur)',
      '🧭 Sécurité & Accès déplacé de Paramètres → sidebar sous Administration (entre Administration et Demandes d\'accès)',
    ],
  },
  {
    version: '1.6.1',
    date: '2026-04-12',
    label: 'Audit sécurité — SMTP crypto + RLS + Auth routes',
    features: [
      '🔐 SMTP password chiffré AES-256-GCM (lib/smtp-crypto.ts) — rétrocompatible avec configs existantes',
      '🔑 ADMIN_EMAIL + SMTP_ENCRYPTION_KEY ajoutées en variables Vercel (chiffrées)',
      '🛡️ RLS fixes DB : logs_acces SELECT authenticated, pipeline_rappels UPDATE filtré user_id, entretiens policies simplifiées, candidates RLS activé',
      '🔒 Auth guard (lib/auth-guard.ts) : requireAuth() sur 7 routes API sans protection (pipeline/clear, logs, matching, pipeline/stages, notes, clients, candidats)',
      '🗓️ Fix date d\'ajout candidat : created_at ajouté dans ALLOWED_COLS (api/candidats/[id])',
      '⏱️ Fix timer inactivité : persistance localStorage — déconnexion immédiate si délai dépassé à la réouverture',
    ],
  },
  {
    version: '1.6.0',
    date: '2026-04-11',
    label: 'Milestone — Audit sécurité + Missions + Pipeline v2',
    features: [
      '🔒 Audit sécurité complet : RLS logs_activite restreint, ADMIN_EMAIL hardcodé supprimé, 10 catch vides corrigés, 4 librairies DnD mortes supprimées',
      '📊 Page Missions : CRUD complet, stats marge brute/coefficient, bilan mensuel avec jours fériés cantonaux (Easter algo, 8 cantons)',
      '🔄 Sync Quadrigis via Cowork : validation manuelle (missions_pending), tabs Mises à jour, badge sidebar',
      '🏗️ Pipeline refonte complète : grille 3 colonnes, onglets consultants + métiers avec compteurs, rappels permanents, ModifierModal',
      '📦 Import bulk aligné avec import normal : second avis, rotation 180°, matching noms composés, auto-attach non-CV',
      '🔀 Fusion doublons robuste : RPC jsonb→text[], méthode 3 noms composés, documents préservés',
      '🔍 Recherche FTS v3 : GIN + trigrammes, unaccent, 14+ champs, notes_candidat inclus',
      '👁️ Non vus cross-device : table candidats_vus Supabase, merge localStorage→DB',
      '🎨 Login redesign + Landing page : auth card Framer Motion, hero/strip/features/beta/footer, pages légales',
      '⏱️ Timer inactivité 25min + Fix OTP bypass critique',
      '🏢 Recherche client : Claude web_search (zefix.ch, local.ch) — remplacement Zefix API (403)',
    ],
  },
  {
    version: '1.5.46',
    date: '2026-04-11',
    label: 'Audit qualité — nettoyage + sécurité',
    features: [
      'Suppression console.log debug dans CVCustomizer.tsx',
      'Suppression chemins absolus hardcodés dans tsconfig.json (ancien Desktop/TALENTFLOW)',
      'Suppression 4 librairies DnD inutilisées (-7 packages)',
      'console.warn ajouté dans 10 catch {} vides (logActivity fire-and-forget) pour debugging',
      'Fix middleware.ts : suppression hardcoded ADMIN_EMAIL fallback (sécurité)',
      'Fix RLS logs_activite : allow_all_logs → SELECT+INSERT only (suppression DELETE/UPDATE pour authenticated)',
    ],
  },
  {
    version: '1.5.45',
    date: '2026-04-11',
    label: 'Fix recherche client Zefix+IA',
    features: [
      'Modèle Claude mis à jour : claude-sonnet-4-6',
      'Données structurées (adresse, NPA, ville, canton) lues directement depuis Zefix (fiables)',
      'Téléphone + site web via web_search_20250305 (recherche web temps réel) — plus d\'hallucination',
      'Secteur d\'activité via un seul appel Claude groupé (connaissance générale)',
      'Deux appels en parallèle (secteurs + contacts) pour limiter la latence',
      'Fallback Claude-only avec web search quand Zefix ne trouve rien',
      'maxDuration 30→60s pour absorber les web searches',
    ],
  },
  {
    version: '1.5.44',
    date: '2026-04-11',
    label: 'Missions — validation manuelle des propositions Quadrigis',
    features: [
      'Table missions_pending : propositions en attente avec type create|update, changes jsonb avant/apres, validation pending|ignored',
      'POST /api/missions/sync-quadrigis : compare avec missions existantes, crée missions_pending (jamais écrit directement dans missions)',
      'GET /api/missions/pending : liste pending + ignored + count pour badge',
      'POST /api/missions/pending/[id]/confirm : INSERT ou UPDATE dans missions + matching candidat/client + DELETE pending',
      'POST /api/missions/pending/[id]/ignore : met en ignored (garde dans historique)',
      'POST /api/missions/pending/[id]/restore : remet en pending pour revalidation',
      'Page Missions : tabs Missions | Bilan | Mises à jour avec badge rouge count',
      'Tab Mises à jour : cards create (➕) et update (✏️) avec diff avant→apres colorisé, [Confirmer] [Ignorer]',
      'Section Historique ignoré (collapsible) avec bouton [↩ Restaurer]',
      'Sidebar : badge rouge numérique sur Missions si pending > 0, écoute missions:pending-changed',
    ],
  },
  {
    version: '1.5.43',
    date: '2026-04-11',
    label: 'Missions — route sync Quadrigis',
    features: [
      'POST /api/missions/sync-quadrigis — reçoit une mission depuis Cowork (lecture Quadrigis)',
      'Logique upsert par numero_quadrigis : UPDATE si trouvé, INSERT sinon',
      'UPDATE : date_debut, date_fin, coefficient, marge_brute, statut — marge_avec_lpp préservée si déjà renseignée',
      'INSERT : matching candidat par prénom+nom (2 essais d\'ordre), matching client par nom_entreprise ilike',
      'normalizeStatut() : mappe les valeurs Quadrigis → en_cours | annulee | terminee',
      'Utilise createAdminClient (service role) — pas de session browser requise',
      'Migration DB : ALTER TABLE missions ADD COLUMN IF NOT EXISTS numero_quadrigis text UNIQUE',
    ],
  },
  {
    version: '1.5.42',
    date: '2026-04-11',
    label: 'Missions — cards layout fix + jours fériés cantonaux bilan',
    features: [
      'MissionRow : colonnes candidat/client/dates passées en flex shrinkable — bouton supprimer plus jamais coupé',
      'MissionRow : bouton "∞ Indéterminée" réduit à "∞" (icône seule) pour économiser la place',
      'Bilan mensuel : jours fériés cantonaux exclus des jours ouvrables (lib/jours-feries.ts)',
      'Cantons supportés : VS, VD, GE, FR, BE, JU, NE, LU (fallback jours fériés nationaux)',
      'Colonne J. ouv. : indicateur violet "-X VD" avec tooltip listant les fériés exclus',
      'API GET /api/missions : join clients!client_id(canton) → champ client_canton retourné',
    ],
  },
  {
    version: '1.5.41',
    date: '2026-04-11',
    label: 'Missions — marge LPP, heures éditables, Mission indéterminée',
    features: [
      'Bilan : formule marge_avec_lpp — si mission > 3 mois ET marge_avec_lpp renseignée → taux LPP utilisé (badge LPP violet dans la colonne)',
      'Bilan : heures modifiables par ligne — input numérique, marge brute estimée recalculée en temps réel',
      'MissionRow : badge LPP violet sur le statut si LPP actif',
      'MissionRow : bouton "Indéterminée" sur les missions Fin de Mission → PATCH date_fin=null',
      'Modal : champ Marge avec LPP (CHF/h) en grille côte à côte avec Marge brute',
    ],
  },
  {
    version: '1.5.40',
    date: '2026-04-11',
    label: 'Missions — refonte liste + bilan semaines',
    features: [
      'Suppression des onglets En Mission / Sans Emploi → liste unifiée toutes missions',
      'Badge "Fin de Mission" rouge quand date_fin passée (en_cours) — coefficient exclu du Total ETP',
      'Tri A-Z par Candidat ET par Client (clic en-tête colonne)',
      'Bilan mensuel : vue "Mois complet" + vue "Par semaine" avec sélecteur',
      'Résumé semaines : candidats actifs, coeff moyen, coeff total par semaine',
      'Renommage Marge nette → Marge brute dans le bilan',
      'Colonne Client dans le bilan détail',
      'Marge CHF : affiche les centimes quand valeur décimale (ex: 6.52)',
      'Prénom avant Nom : candidat_nom mis à jour en DB (prenom + nom)',
    ],
  },
  {
    version: '1.5.39',
    date: '2026-04-11',
    label: 'Missions — import Quadrigis + Bilan mensuel + filtres',
    features: [
      'Import Quadrigis : 34 missions importées avec matching candidats/clients DB, coefficient 1.0 / 0.5',
      'Bilan mensuel — section collapsible : jours ouvrables prorata, ETP actifs, marge nette estimée',
      'Table bilan : Candidat → Poste → Coeff → Jours → Heures → Marge/h → Marge nette, "À compléter" orange si marge=0',
      'Filtre par métier (select) + effacement rapide',
      'Tri par nom candidat (A-Z / Z-A) via clic sur l\'en-tête colonne',
      'Lien vers la fiche candidat depuis la liste et le bilan',
      'Suppression bouton Import Notion (plus utilisé)',
    ],
  },
  {
    version: '1.5.36',
    date: '2026-04-11',
    label: 'Page Missions — suivi placements + import Notion',
    features: [
      'Page Missions (admin only) — suivi des placements candidats avec KPIs marge',
      'Stats live : missions actives, marge en cours, marge totale, coefficient moyen',
      'CRUD complet : ajout / modification / suppression avec modals createPortal',
      'Tabs : En cours / Terminées / Annulées / Toutes avec compteurs',
      'Import Notion : liste les bases disponibles, importe automatiquement via correspondance flexible de colonnes',
      'API : GET/POST /api/missions, PATCH/DELETE /api/missions/[id], POST /api/missions/import-notion',
      'Sidebar : entrée Missions avec TrendingUp icon (admin only)',
    ],
  },
  {
    version: '1.5.35',
    date: '2026-04-11',
    label: 'Import en masse — alignement complet avec import normal (8 fixes)',
    features: [
      'Fix CRITIQUE : détection doublons ajoutée — email → téléphone → nom+prénom (OR tous mots) avant création candidat',
      'Fix CRITIQUE : cv_texte_brut stocké — la recherche FTS trouve maintenant les candidats importés en masse',
      'Fix CRITIQUE : second avis non-CV — certificats/diplômes détectés via filename + patterns stricts, auto-attachés si candidat trouvé',
      'Fix CRITIQUE : détection cvScore=0 — diplôme/certificat mal classifié "cv" refusé avec message explicite',
      'Fix MEDIUM : import_status="a_traiter" défini à la création (onglet "À traiter")',
      'Fix MEDIUM : genre extrait via normaliserGenre(analyse.genre)',
      'Fix MEDIUM : photos DOCX et DOC extraites (uniquement si CV)',
      'Fix LOW : mapDocumentTypeBulk complété — reference, contrat, bulletin_salaire ajoutés',
      'Doublon CV : smart update (archive ancien CV, fusionne compétences/langues/expériences)',
      'Log activité enrichi : créés / mis à jour / docs ajoutés / erreurs',
    ],
  },
  {
    version: '1.5.34',
    date: '2026-04-10',
    label: 'Fix import normal — certificats bloqués par détection diplôme + matching prénoms composés',
    features: [
      'Fix : certificats importés via "Importer Candidat/s" bloqués par la détection diplôme (cvScore=0) → skip si l\'IA a déjà classifié comme non-CV',
      'Fix : matching prénoms composés — vérifie TOUS les mots du prénom (pas juste le premier) → "Marjorie Yanina" match "Yanina" en base',
      'Fix : documents non-CV avec 1 seul match de nom → auto-attach au candidat (pas de confirmation requise)',
    ],
  },
  {
    version: '1.5.33',
    date: '2026-04-10',
    label: 'Alignement import normal ↔ OneDrive — second avis, rotation 180°, types documents, created_at',
    features: [
      'Fix : second avis ajouté à l\'import normal — détection certificat/diplôme par filename et contenu strict (comme OneDrive)',
      'Fix : rotation 180° ajoutée à OneDrive sync — si analyse vide après vision, essaye le PDF retourné (comme import normal)',
      'Fix : types documents alignés lowercase — OneDrive stockait PascalCase ("Certificat") non reconnu par l\'UI → maintenant "certificat"',
      'Fix : types manquants ajoutés — reference, contrat, bulletin_salaire dans DocumentType + mapDocumentType + detectDocCategory',
      'Fix : created_at non mis à jour pour doc non-CV dans import normal (seul le CV d\'origine compte)',
    ],
  },
  {
    version: '1.5.32',
    date: '2026-04-10',
    label: 'Fix fusion 500 (jsonb→text[]) + fix matching méthode 3 (noms composés)',
    features: [
      'Fix CRITICAL : fusion RPC 500 — competences/tags/langues sont text[] mais RPC assignait du jsonb brut → ARRAY(jsonb_array_elements_text()) corrige le cast',
      'Fix CRITICAL : méthode 3 matching trop lâche — "Marmolejo Zambrano" matchait "Calderon Zambrano" et "Marina Zambrano" au lieu de "Yanina Marmolejo"',
      'Fix : requête DB méthode 3 — OR sur tous les mots du nom (pas juste le dernier) → "Marmolejo Zambrano" cherche %marmolejo% OR %zambrano%',
      'Fix : filtre méthode 3 strict — exige nom word match + prenom word match (startsWith ≥4 chars, pas de préfixe 3 chars)',
      'Fix : nomsSimilaires compound fallback — exige BOTH nom ET prenom DB dans le nom complet parsé (était: un seul suffisait)',
      'Fix : document non-CV classé "Autre" au lieu du type IA — detectDocCategory recalculait avec texteCV vide (scans), maintenant utilise le docType déjà détecté par l\'IA',
    ],
  },
  {
    version: '1.5.31',
    date: '2026-04-10',
    label: 'OneDrive matching méthode 3 fix + diagnostic fusion RPC',
    features: [
      'Fix : méthode 3 matching (nom+prénom) utilise nomsSimilaires() au lieu d\'un filtre strict nom === nom',
      'Fix : fallback substring — si le nom DB (>= 4 chars) apparaît dans le nom complet parsé → match accepté',
      'Ex: parsé "Marmolejo Zambrano" → DB "Marmolejo" → trouvé (était rejeté par le filtre strict)',
      'Diagnostic : logs détaillés sur la fusion RPC (START, result, ERROR detail, CATCH exception)',
    ],
  },
  {
    version: '1.5.30',
    date: '2026-04-10',
    label: 'Fusion doublons — fix données perdues (notes, entretiens, rappels, nom, pipeline)',
    features: [
      'Fix HIGH : notes_candidat transférées au candidat conservé avant suppression du doublon (étaient perdues par CASCADE)',
      'Fix HIGH : entretiens transférés au candidat conservé avant suppression',
      'Fix MEDIUM : pipeline_rappels transférés au candidat conservé avant suppression',
      'Fix MEDIUM : nom et prénom fusionnés — le choix utilisateur "nom_complet" est respecté (était ignoré)',
      'Fix MEDIUM : pipeline_consultant et pipeline_metier inclus dans la fusion',
      'Fix MEDIUM : onedrive_fichiers rattachés au candidat conservé (évite re-création par cron)',
      'Fix LOW : UPDATE documents avec gestion d\'erreur explicite (log si échec)',
      'RPC merge_candidats : 7 étapes (UPDATE candidat, pipeline, notes, entretiens, rappels, onedrive_fichiers, DELETE)',
    ],
  },
  {
    version: '1.5.29',
    date: '2026-04-10',
    label: 'OneDrive sync — 5 fixes audit (cv_texte_brut, boucle >50 erreurs, race tel, created_at, nomsSimilaires)',
    features: [
      'Fix HIGH : cv_texte_brut ajouté à l\'UPDATE candidat existant — élimine la boucle de re-update infinie à chaque cron',
      'Fix MEDIUM : boucle sync manuelle s\'arrête si aucune activité réelle, même avec remaining > 0 (>50 fichiers erreur)',
      'Fix MEDIUM : race check par téléphone ajouté — évite les doublons quand 2 fichiers du même candidat sont traités en parallèle',
      'Fix LOW : created_at non mis à jour lors de l\'ajout d\'un document non-CV (certificat/diplôme) — évite de backdater le candidat',
      'Fix LOW : nomsSimilaires rejette si le candidat DB n\'a pas de nom (évite faux positifs sur match email/tel)',
    ],
  },
  {
    version: '1.5.28',
    date: '2026-04-10',
    label: 'OneDrive sync — detectDocCategory second avis après l\'IA',
    features: [
      'Fix : documents non-CV avec nom générique ("Scanné 6 janv...") maintenant détectés correctement',
      'Second avis après parsing IA : si l\'IA retourne "cv", vérification par nom de fichier puis par contenu strict',
      'Patterns contenu stricts : "certificat de travail", "lettre de motivation", "bulletin de salaire", etc. (pas de faux positifs sur CVs)',
      'Nom de fichier : utilise detectDocCategory existant (mots-clés simples suffisent pour les noms de fichier)',
      'Bilingue FR/DE : patterns suisses allemands inclus (Arbeitszeugnis, Aufenthaltsbewilligung, etc.)',
    ],
  },
  {
    version: '1.5.27',
    date: '2026-04-10',
    label: 'Fusion doublons — fix documents perdus + CV archivé',
    features: [
      'Fix : documents[] du candidat supprimé maintenant transférés vers le candidat conservé (étaient perdus)',
      'Fix : CV non-choisi archivé dans documents[] avant d\'être écrasé (avec nom de fichier d\'origine)',
      'Fix : UPDATE documents séparé après RPC (le RPC merge_candidats ne mettait pas à jour documents[])',
      'Déduplication : union documents[] par url ET name (pas de doublon si même fichier dans les deux profils)',
    ],
  },
  {
    version: '1.5.26',
    date: '2026-04-10',
    label: 'OneDrive sync manuel — fix boucle infinie sur fichiers en erreur',
    features: [
      'Fix : sync manuelle ne boucle plus sur les fichiers "introuvable" — erreurs exclues du compteur d\'activité',
      'Fix : traite_le maintenant écrit lors d\'une erreur → retryAlwaysIds optimization fonctionne correctement',
      'Avant : erreur → loop continue → re-essai → erreur → boucle infinie jusqu\'à Stop manuel',
      'Après : erreur → loop s\'arrête si aucune autre activité réelle (créations/mises-à-jour/réactivations)',
    ],
  },
  {
    version: '1.5.25',
    date: '2026-04-10',
    label: 'OneDrive sync — fix doublons candidats + documents dupliqués',
    features: [
      'Fix doublon : méthode matching téléphone — suppression du filtre prenom ilike (éliminait les noms composés/inversés)',
      'Fix doublon : filtre par dernière partie du nom (plus fiable que prénom) + limit 300',
      'Fix doublon : nomsSimilaires() étendu — vérifie si nom/prénom DB apparaît dans le nom complet parsé (ex: "Marjorie Yanina Marmolejo Zambrano" → "Yanina Marmolejo")',
      'Fix documents : déduplication avant documents.push() — vérifie url ET name avant d\'ajouter',
      'Fix documents : même déduplication pour l\'archivage de l\'ancien CV (move to documents[])',
    ],
  },
  {
    version: '1.5.24',
    date: '2026-04-09',
    label: 'Sécurité critique — fix bypass OTP via bouton Retour',
    features: [
      'Fix critique : vérification des credentials déplacée côté serveur (API /api/auth/verify-password)',
      'Aucune session browser créée lors de la saisie email + mot de passe — élimine la fenêtre de vulnérabilité',
      'Session Supabase créée uniquement après OTP vérifié ou grace period confirmée',
      'Admin client (persistSession:false) utilisé côté serveur — aucun cookie auth posé dans la réponse HTTP',
      'Invalidation automatique de la session serveur créée pour la vérification (fire & forget)',
    ],
  },
  {
    version: '1.5.23',
    date: '2026-04-09',
    label: 'Timer inactivité — popup logout automatique après 25 min',
    features: [
      'Timer inactivité : popup d\'avertissement après 25 min (mousemove, keydown, click, scroll, touchstart)',
      'Countdown 2:00 avec barre de progression, rouge sous 30 secondes',
      'Boutons "Rester connecté" (reset timer) et "Se déconnecter" (logout immédiat)',
      'Logout automatique à 0:00 → signOut + redirect /login',
      'Désactivé automatiquement pendant un import en masse',
    ],
  },
  {
    version: '1.5.22',
    date: '2026-04-09',
    label: 'Pipeline — métiers par consultant + compteurs + suppression recherche',
    features: [
      'Pipeline : sous-onglets métiers filtrés par consultant actif (João voit ses métiers, Seb les siens)',
      'Pipeline : compteur par onglet consultant (ex: João 7)',
      'Pipeline : compteur par sous-onglet métier (ex: Sanitaire 3)',
      'Pipeline : suppression de la barre de recherche',
    ],
  },
  {
    version: '1.5.21',
    date: '2026-04-09',
    label: 'Pipeline — fixes photos, icône CV, rappels permanents',
    features: [
      'Pipeline : fix photo — initiales toujours visibles en fond, image par-dessus (onError propre)',
      'Pipeline : bouton aperçu CV → icône Eye distincte du bouton Fiche (FileText)',
      'Pipeline : rappels permanents — toast duration:Infinity avec boutons Valider + Fermer',
      'Sidebar : lien Entretiens / Suivi masqué (code conservé)',
    ],
  },
  {
    version: '1.5.20',
    date: '2026-04-09',
    label: 'Pipeline — Refonte v2 (métiers catégorisés, ModifierModal, bulk depuis liste)',
    features: [
      'Pipeline : sous-onglets métiers dynamiques depuis candidats + "Autres" pour sans-métier',
      'Pipeline : AddToPipelineModal — recherche toute la DB, métiers groupés par catégorie',
      'Pipeline : ModifierModal — changer consultant + métier sur une card existante',
      'Pipeline : bouton Modifier (Settings2) sur chaque card',
      'CandidatsList : bouton Pipeline remplacé — modal consultant + métier (datalist)',
    ],
  },
  {
    version: '1.5.19',
    date: '2026-04-09',
    label: 'Pipeline — Refonte complète (grille + consultants + métiers + rappels)',
    features: [
      'Pipeline : suppression DnD/Kanban, grille 3 colonnes responsive',
      'Pipeline : onglets consultants (Tous / João / Seb) + sous-onglets métiers dynamiques',
      'Pipeline : cards enrichies — photo, localisation (rouge), âge, badge métier, notes preview, icône rappel',
      'Pipeline : RappelModal — date/heure + note, icône Bell colorée si rappel actif',
      'Pipeline : AddToPipelineModal — recherche candidat + sélection consultant + métier libre',
      'Pipeline : notifications rappels via setInterval 60s (toast avec "Marquer fait")',
      'Pipeline : NoteModal réutilisé depuis createPortal',
      'DB : colonnes pipeline_consultant + pipeline_metier sur candidats',
      'DB : table pipeline_rappels (uuid, candidat_id, user_id, rappel_at, note, done) + RLS',
      'API : /api/pipeline/rappels GET/POST/PATCH/DELETE',
      'API : /api/candidats supporte statut_pipeline=true (not null) + colonnes consultant/metier',
    ],
  },
  {
    version: '1.5.15',
    date: '2026-04-09',
    label: 'Fix badge sidebar — ensureInit + couleur labels Menu/Compte',
    features: [
      'Fix : race condition badge sidebar — ensureInit() garantit que viewedAllAt est chargé avant le premier calcul',
      'Fix : un seul appel API /candidats/vus partagé entre Sidebar et CandidatsList (promise cachée)',
      'Fix : sidebar affiche maintenant le bon chiffre dès le premier rendu (plus de flash 5 → 2)',
      'Fix : labels "Menu" et "Compte" sidebar — opacité rgba(255,255,255,0.22) → 0.45 (plus lisibles)',
    ],
  },
  {
    version: '1.5.14',
    date: '2026-04-09',
    label: 'Fix badge sidebar non-vus + couleur demande-acces',
    features: [
      'Fix : badge sidebar candidats — utilise maintenant hasBadge(id, created_at, viewedSet, viewedAllAt) au lieu de viewed.has(id)',
      'Fix : sidebar ignorait viewedAllAt — le timestamp "Tout marquer vu" est maintenant pris en compte',
      'Fix : CandidatsList dispatch badges-changed après initViewedFromDB() → sidebar se resync immédiatement',
      'Fix : page /demande-acces — couleur #F7C948 → #F5A623 (cohérence orange app)',
    ],
  },
  {
    version: '1.5.13',
    date: '2026-04-09',
    label: 'Login redesign — glassmorphism dark + Framer Motion',
    features: [
      'Pages auth redesignées : fond blanc #FFFDF5 + orbes animées subtiles, card blanche centrée',
      'Card login : border cream, shadow subtile, logo neo-brutalist orange, animations Framer Motion',
      'Inputs : focus glow orange #F5A623, bouton orange avec shadow offset noir',
      'Stagger Framer Motion sur tous les champs (fadeUp delay progressif)',
      'Footer légal discret sur chaque page : liens CGU + Confidentialité',
      'Pages converties : /login, /verify-email, /accepter-invitation (états: loading, expired, form, succès)',
      '/register : redirige vers /demande-acces (inchangé)',
      'Panel gauche branding supprimé sur toutes les pages — card centrée full-page',
      'auth.css --y: #F7C948 → #F5A623 (cohérence app)',
    ],
  },
  {
    version: '1.5.12',
    date: '2026-04-09',
    label: 'Landing page redesign + pages légales provisoires',
    features: [
      'Landing : couleur #F7C948 → #F5A623 (cohérence avec l\'app)',
      'Landing : Hero — CTA "Demander une démo" + "Se connecter", social proof avatars',
      'Landing : Strip — stats mises à jour (OneDrive, Matching IA, Pipeline, LPD)',
      'Landing : Features — 12 cartes mises à jour (OneDrive Sync, Matching IA, LPD/RGPD)',
      'Landing : Section bêta — remplace Pricing, encart "en phase de développement" + CTA démo',
      'Landing : Footer redesigné — 3 colonnes (brand, navigation, légal) avec liens CGU/Confidentialité/Mentions',
      'Navbar : liens "Fonctionnalités" + "Contact" ajoutés',
      'Pages légales provisoires : /cgu, /confidentialite, /mentions-legales (LPD suisse)',
    ],
  },
  {
    version: '1.5.11',
    date: '2026-04-09',
    label: 'Fix non-vus — migration viewedAllAt localStorage → Supabase',
    features: [
      'Migration one-shot : candidats_viewed_all_at localStorage → user_metadata Supabase (fix 491 faux non-vus)',
      'PATCH /api/candidats/vus — endpoint dédié pour mettre à jour le timestamp "tout vu" sans toucher les lignes',
    ],
  },
  {
    version: '1.5.10',
    date: '2026-04-09',
    label: 'Drapeaux téléphone — SVG cross-platform (flag-icons)',
    features: [
      'Drapeaux pays sur numéros de téléphone via flag-icons CSS (SVG) — fonctionne sur Windows',
      'Centralisation detectAndFormat() dans lib/phone-format.ts (3 duplications supprimées)',
      'Rendu <span class="fi fi-ch"> au lieu d\'emojis Unicode — affichage cohérent Mac/Windows/Linux',
    ],
  },
  {
    version: '1.5.9',
    date: '2026-04-09',
    label: 'Non vus — migration localStorage → Supabase DB cross-device',
    features: [
      'Table candidats_vus (user_id, candidat_id) avec RLS par utilisateur',
      'Sync automatique localStorage → DB au premier chargement (migration one-shot)',
      'hasBadge tient compte du timestamp "Tout marquer vu" stocké en user_metadata',
      'Badges cohérents cross-device : Mac + Windows partagent le même état',
    ],
  },
  {
    version: '1.5.8',
    date: '2026-04-09',
    label: 'Recherche — DB indexes + unaccent + champs complets',
    features: [
      'Index GIN fts (tsvector french) + index trigramme sur nom/prénom/titre/localisation',
      'unaccent partout — macon trouve maçon, electricien → électricien',
      'Recherche dans compétences, tags, expériences, formations, téléphone (en plus des champs existants)',
      'Suppression linkedin et années d\'expérience (non utilisés sur la plateforme)',
    ],
  },
  {
    version: '1.5.7',
    date: '2026-04-09',
    label: 'Fix recherche candidats — 6 correctifs',
    features: [
      'Fix 1 : pagination recherche — result_offset manquant en DB (page 2+ retournait toujours page 1)',
      'Fix 2 : multi-mots — chaque mot cherché séparément avec AND (était phrase exacte)',
      'Fix 3 : sync filtreMetier ↔ filterMetier bidirectionnel (dropdown liste et filtres avancés)',
      'Fix 4 : RPC utilise fts @@ plainto_tsquery (GIN index) + ILIKE sur cv_texte_brut / resume_ia',
      'Fix 4 : RPC retourne total_count (était toujours 0 en mode recherche)',
      'Fix 5 : booléen ET/AND → envoyé au serveur (FTS complet) ; OU/SAUF reste client-side',
      'Fix 5 : corpus booléen client inclut maintenant resume_ia',
      'Fix 6 : fallback ILIKE inclut resume_ia',
    ],
  },
  {
    version: '1.5.6',
    date: '2026-04-08',
    label: 'Documents modal centré + Pipeline redesign + UI fixes',
    features: [
      'Documents : panel latéral → modal centré (createPortal, position: fixed, animation scaleIn)',
      'Documents : s\'affiche correctement peu importe le scroll ou les animations Framer Motion parentes',
      'Candidats : barre de sélection multi — 2 rangées, couleurs distinctes par action, glow orange correct',
      'Candidats : bouton "Ajouter au Pipeline" dans la sélection (onglet Actif uniquement)',
      'Candidats : tooltip notes — jusqu\'à 3 notes avec date + séparateur',
      'Pipeline : colonnes flex:1 (remplissent l\'espace), 2 cards par colonne, mode liste supprimé',
      'Pipeline : notes toujours visibles sur les cards, actions au survol uniquement',
      'Fix : photos pipeline — handler onError avec fallback initiales',
      'Fix : RLS app_settings — sauvegarde étapes via /api/pipeline/stages + createAdminClient()',
      'Fix : glow inputs — orange rgba(245,167,35,0.15) au lieu du jaune fluo',
      'Fix : métier sync liste ↔ fiche (invalidation queryKey manquante)',
      'Fix : CV preview — createPortal pour échapper Framer Motion transform',
    ],
  },
  {
    version: '1.5.5',
    date: '2026-04-08',
    label: 'Fix badges, CV preview, MetierPopover, notes tooltip',
    features: [
      'Fix : badge sidebar candidats — #EF4444 rouge au lieu de #F5A623 orange',
      'Fix : badge non-vus onglets — z-index 50, visible au-dessus du bouton "À traiter"',
      'Fix : aperçu CV — panneau centré sur la card via e.clientY + ref DOM directe (bypass React), panelH max 55vh/520px',
      'Fix : tooltip notes — createPortal dans document.body, position fixed viewport-aware',
      'Fix : MetierPopover — createPortal + anchorRect au clic, position fixed z-index 9999',
      'Fix : Sidebar.tsx — #FFE800 → #F5A623 (2 occurrences)',
    ],
  },
  {
    version: '1.5.3',
    date: '2026-04-08',
    label: 'Revert UI redesign + Fix MetierPopover',
    features: [
      'Revert : couleur primaire #FFE800 → #F5A623 (retour à l\'orange original)',
      'Revert : tokens CSS — suppression blocs dark/light séparés, retour au :root original',
      'Revert : sidebar — suppression gradient, border-left nav links, transitions cubic-bezier',
      'Revert : boutons — .neo-btn border-radius 100px, .neo-btn-yellow border noire + shadow brutalist',
      'Revert : KPI cards dark — suppression backdrop-filter blur',
      'Fix : MetierPopover — position fixed + z-index 9999, plus caché derrière les cards',
    ],
  },
  {
    version: '1.5.2',
    date: '2026-04-08',
    label: 'Sécurité RLS + Pipeline enrichi',
    features: [
      'Sécurité : RLS activé sur 5 tables (candidats, app_settings, email_otps, jobs, onedrive_fichiers) avec policies service_role + authenticated',
      'Pipeline : recherche dans le board (champ manquant corrigé)',
      'Pipeline : cards enrichies — photo, téléphone cliquable, badges CFC/Engagé, avatar 44px, nom 14px',
      'Pipeline : mode grille (2 cards côte à côte, toggle liste/grille persisté en localStorage)',
      'Pipeline : scroll horizontal amélioré — gradient fade, scrollbar fine stylée 6px',
      'Pipeline : icône Aperçu CV différenciée (FileText au lieu de Eye dupliqué)',
    ],
  },
  {
    version: '1.5.1',
    date: '2026-04-08',
    label: 'Fix sync métier liste ↔ fiche',
    features: [
      'Fix : métier assigné depuis la liste candidats maintenant reflété immédiatement à l\'ouverture de la fiche (invalidation queryKey [\'candidat\', id] manquante)',
    ],
  },
  {
    version: '1.5.0',
    date: '2026-04-08',
    label: 'OneDrive Sync v2 — Refonte complète',
    features: [
      'Historique fichiers groupé par jour (accordion, 5 catégories : créés / mis à jour / réactivés / documents / erreurs)',
      'Catégorisation automatique des documents non-CV (Certificat · Diplôme/Formation · Lettre de motivation · Permis · Référence · Contrat · Bulletin de salaire)',
      'Rapport de synchronisation détaillé (créés / mis à jour / réactivés / déjà à jour / erreurs)',
      'Identification robuste — 5 méthodes, insensible aux accents, tolérance prénom préfixe, désambiguïsation multi-candidats',
      'Logique mise à jour CV basée sur le contenu (500 chars) — SKIP / réactivation / update complet',
      'Batch 50 CVs/cycle, auto-refresh 5s/30s, retry automatique documents "candidat introuvable"',
      'Fix boucle infinie : memeDate cassé (format Z vs +00:00) + certificats retentés à l\'infini',
      'Fix race condition lors d\'imports parallèles, déduplication suffixes [45]/(45)',
      'Fix cron : Authorization header manquant → 401 permanent',
      'Fix filtre "Non vus" perdu au retour de la fiche candidat',
    ],
  },
  {
    version: '1.4.0',
    date: '2026-04-07',
    label: 'Entretiens, Hardening & Activités',
    features: [
      'Entretiens / Suivi : page redessinée en vue liste, rappels avec date, notifications popup, badge sidebar',
      'Outil "Corriger photos" : extraction batch DOCX/DOC/PDF, UI 3 boutons, historique portraits cliquables',
      'Activités : logs unifiés (table activites), WhatsApp loggué, fusion doublons loggée, recherche PostgreSQL',
      'Badges "non vus" animés par onglet (Actif / À traiter / Archivé)',
      'Sync cache liste ↔ fiche (CFC, engagé, étoiles, notes)',
      'Fix recherche : URL overflow 650+ IDs, filtres CFC et Déjà engagé serveur-side',
      '15 corrections hardening : rate limiting, circuit breaker, FK cascade, PDFs chiffrés, RLS, erreurs masquées',
      'Dark mode : corrections dans Paramètres, Profil, Logs, Doublons, Intégrations, Documents',
    ],
  },
  {
    version: '1.3.0',
    date: '2026-03-29',
    label: 'Mobile, France Travail & Planning',
    features: [
      'Mobile : layout responsive complet, HEIC/HEIF, touch, boutons agrandis, viewer CV masqué sous 768px',
      'France Travail : formulaire Word fidèle, envoi Resend, CC automatique, historique des envois',
      'Planning : refonte majeure — périodes, ETP par semaine, marge horaire, tri colonnes, candidats hors-système',
      'Parsing IA : détection date naissance, genre, permis, documents non-CV (certificats, permis nacelle…)',
      'Doublons : carte enrichie (photo, expériences, stats, badge source)',
      'Cross-device : "Tout marquer vu" synchronisé, OTP grace 4h (cookie httpOnly HMAC-SHA256)',
    ],
  },
  {
    version: '1.2.0',
    date: '2026-03-24',
    label: 'OneDrive v1, Doublons & Mailing',
    features: [
      'OneDrive Sync v1 : récursif, smart update (mise à jour / réactivation), images JPG/PNG/WebP',
      'Doublons : fusion atomique (RPC), actions individuelles, ré-analyse par paire',
      'Mailing géographique : filtre distance, tri km, badge code-couleur, CV personnalisé en PJ via Microsoft Graph',
      'Activités : timeline collaborative, filtres type/date, onglets Pipeline/Messages/Candidats/Imports',
      'Métiers : partagés via Supabase, catégories colorées, filtre avancé',
      'Recherche booléenne ET/OU/SAUF, filtre étoiles, badges CFC, dates de fichier DD.MM.YYYY',
      'Outlook per-user : chaque utilisateur connecte son propre compte',
    ],
  },
  {
    version: '1.1.0',
    date: '2026-03-22',
    label: 'Import IA, Recherche & Documents',
    features: [
      'Import IA multi-modèle (Claude, Gemini, Groq), parsing masse ZIP/PDF/DOCX/DOC en arrière-plan',
      'Classification IA : CV, certificat, diplôme, formation, attestation, permis',
      'Recherche full-text PostgreSQL (compétences, expériences, formations, CV brut, résumé IA)',
      'Pagination serveur (20/50/100), page mémorisée, filtres avancés (permis, genre, âge, langue)',
      'Panel Documents : catégories, drag & drop, CV principal, upload depuis la fiche',
      'Zoom CV qualité HD (iframe agrandie, scroll, drag, rotation)',
      'Score étoiles 0-5, crop photo manuel, re-parsing additif',
      'Module Clients : 1207 entreprises, fiche, filtres, recherche',
    ],
  },
  {
    version: '1.0.0',
    date: '2026-03-21',
    label: 'Version stable initiale',
    features: [
      'Candidats : CRUD complet, fiche détaillée, CV viewer, photos, doublons, pipeline Kanban',
      'Import CV : PDF/DOCX/DOC, parsing IA (Claude), extraction photo, détection doublons',
      'Pipeline Kanban : drag & drop, étapes, matching IA candidat/offre',
      'Communications : email (Resend/SMTP), WhatsApp Business, SMS, templates',
      'Microsoft 365 OAuth : synchronisation Outlook, import CVs depuis emails',
      'Authentification OTP email (HMAC-SHA256), gestion des accès',
      'Interface L\'Agence SA (thème noir & jaune), dark mode, sidebar',
    ],
  },
]
